# Generated by Django 4.1.4 on 2022-12-28 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('standard', models.CharField(default='', max_length=10)),
                ('division', models.CharField(default='', max_length=10)),
                ('gr_no', models.IntegerField(default='')),
                ('gender', models.CharField(default='', max_length=10)),
                ('dob', models.DateField()),
                ('contact', models.IntegerField(default='')),
                ('address', models.CharField(default='', max_length=200)),
                ('aadhaar', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_password', models.CharField(default='', max_length=50)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.DateTimeField(auto_now=True)),
                ('date', models.CharField(default='', max_length=100)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.identitycard')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher', models.CharField(default='v', max_length=5)),
                ('division', models.CharField(default='a', max_length=2)),
                ('gender', models.CharField(default='xx', max_length=3)),
                ('profile_picture', models.ImageField(default='', upload_to='profile_pic/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
