# Generated by Django 4.1.4 on 2023-01-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_passwordcollector_delete_collectedpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TextField()),
            ],
        ),
    ]
