# Generated by Django 4.1.4 on 2023-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_contact_delete_collectedpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitycard',
            name='picture',
            field=models.ImageField(default='', upload_to='identity_card_pics/'),
        ),
    ]
