# Generated by Django 4.1.4 on 2023-01-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_identitycard_picture_delete_collectedpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitycard',
            name='picture',
            field=models.ImageField(blank=True, default='/profile_pics/default.webp/', upload_to='identity_card_pics/'),
        ),
    ]
