# Generated by Django 4.1.4 on 2023-01-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_identitycard_dob_dayofyear_internal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CollectedPassword',
        ),
    ]
