# Generated by Django 4.1.4 on 2023-01-30 16:50

import birthday.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('dob_dayofyear_internal', models.PositiveSmallIntegerField(default=None, editable=False, null=True)),
                ('dob', birthday.fields.BirthdayField()),
            ],
        ),
    ]
